// 10 visual themes for StudyMind
// Each theme overrides the CSS custom properties defined in @theme (index.css)
// Rule: text colors are always neutral (grays) — accent only for interactive elements

export const THEMES = {
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    description: 'Azul oscuro con acentos cyan',
    preview: { bg: '#0f172a', accent: '#06b6d4', text: '#f1f5f9' },
    vars: {
      '--color-surface': '#0f172a',
      '--color-surface-alt': '#1e293b',
      '--color-surface-light': '#334155',
      '--color-accent': '#06b6d4',
      '--color-accent-soft': '#0e7490',
      '--color-accent-glow': 'rgba(6, 182, 212, 0.12)',
      '--color-text': '#f1f5f9',
      '--color-text-dim': '#94a3b8',
      '--color-text-muted': '#64748b',
    },
  },
  obsidian: {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Negro puro con acentos violeta',
    preview: { bg: '#09090b', accent: '#a78bfa', text: '#fafafa' },
    vars: {
      '--color-surface': '#09090b',
      '--color-surface-alt': '#18181b',
      '--color-surface-light': '#27272a',
      '--color-accent': '#a78bfa',
      '--color-accent-soft': '#7c3aed',
      '--color-accent-glow': 'rgba(167, 139, 250, 0.10)',
      '--color-text': '#fafafa',
      '--color-text-dim': '#a1a1aa',
      '--color-text-muted': '#71717a',
    },
  },
  aurora: {
    id: 'aurora',
    name: 'Aurora',
    description: 'Azul profundo con verde esmeralda',
    preview: { bg: '#0c1222', accent: '#34d399', text: '#e2e8f0' },
    vars: {
      '--color-surface': '#0c1222',
      '--color-surface-alt': '#162032',
      '--color-surface-light': '#253348',
      '--color-accent': '#34d399',
      '--color-accent-soft': '#059669',
      '--color-accent-glow': 'rgba(52, 211, 153, 0.10)',
      '--color-text': '#e2e8f0',
      '--color-text-dim': '#94a3b8',
      '--color-text-muted': '#64748b',
    },
  },
  ember: {
    id: 'ember',
    name: 'Ember',
    description: 'Carbón oscuro con acentos naranja',
    preview: { bg: '#1c1210', accent: '#f97316', text: '#fafaf9' },
    vars: {
      '--color-surface': '#1c1210',
      '--color-surface-alt': '#292018',
      '--color-surface-light': '#3d3024',
      '--color-accent': '#f97316',
      '--color-accent-soft': '#c2410c',
      '--color-accent-glow': 'rgba(249, 115, 22, 0.10)',
      '--color-text': '#fafaf9',
      '--color-text-dim': '#a8a29e',
      '--color-text-muted': '#78716c',
    },
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean',
    description: 'Azul marino profundo con dorado',
    preview: { bg: '#0a1628', accent: '#fbbf24', text: '#e2e8f0' },
    vars: {
      '--color-surface': '#0a1628',
      '--color-surface-alt': '#142240',
      '--color-surface-light': '#1e3a5f',
      '--color-accent': '#fbbf24',
      '--color-accent-soft': '#d97706',
      '--color-accent-glow': 'rgba(251, 191, 36, 0.10)',
      '--color-text': '#e2e8f0',
      '--color-text-dim': '#94a3b8',
      '--color-text-muted': '#64748b',
    },
  },
  rose: {
    id: 'rose',
    name: 'Rosé',
    description: 'Gris oscuro con acentos rosa',
    preview: { bg: '#1a1118', accent: '#f472b6', text: '#faf5f7' },
    vars: {
      '--color-surface': '#1a1118',
      '--color-surface-alt': '#281c24',
      '--color-surface-light': '#3b2a34',
      '--color-accent': '#f472b6',
      '--color-accent-soft': '#db2777',
      '--color-accent-glow': 'rgba(244, 114, 182, 0.10)',
      '--color-text': '#faf5f7',
      '--color-text-dim': '#a8a0a4',
      '--color-text-muted': '#78707a',
    },
  },
  nord: {
    id: 'nord',
    name: 'Nord',
    description: 'Polar nórdico con azul hielo',
    preview: { bg: '#2e3440', accent: '#88c0d0', text: '#eceff4' },
    vars: {
      '--color-surface': '#2e3440',
      '--color-surface-alt': '#3b4252',
      '--color-surface-light': '#434c5e',
      '--color-accent': '#88c0d0',
      '--color-accent-soft': '#5e81ac',
      '--color-accent-glow': 'rgba(136, 192, 208, 0.10)',
      '--color-text': '#eceff4',
      '--color-text-dim': '#d8dee9',
      '--color-text-muted': '#8690a0',
    },
  },
  academic: {
    id: 'academic',
    name: 'Academic',
    description: 'Claro tipo pergamino con sepia',
    preview: { bg: '#faf8f1', accent: '#92400e', text: '#292524' },
    vars: {
      '--color-surface': '#faf8f1',
      '--color-surface-alt': '#f0ece1',
      '--color-surface-light': '#d6d0c4',
      '--color-accent': '#92400e',
      '--color-accent-soft': '#b45309',
      '--color-accent-glow': 'rgba(146, 64, 14, 0.08)',
      '--color-text': '#292524',
      '--color-text-dim': '#57534e',
      '--color-text-muted': '#a8a29e',
    },
  },
  paper: {
    id: 'paper',
    name: 'Paper',
    description: 'Blanco limpio con azul profesional',
    preview: { bg: '#ffffff', accent: '#2563eb', text: '#1e293b' },
    vars: {
      '--color-surface': '#ffffff',
      '--color-surface-alt': '#f8fafc',
      '--color-surface-light': '#e2e8f0',
      '--color-accent': '#2563eb',
      '--color-accent-soft': '#1d4ed8',
      '--color-accent-glow': 'rgba(37, 99, 235, 0.08)',
      '--color-text': '#1e293b',
      '--color-text-dim': '#475569',
      '--color-text-muted': '#94a3b8',
    },
  },
  moss: {
    id: 'moss',
    name: 'Moss',
    description: 'Verde bosque con acentos lima',
    preview: { bg: '#141c15', accent: '#84cc16', text: '#f0fdf4' },
    vars: {
      '--color-surface': '#141c15',
      '--color-surface-alt': '#1e2b20',
      '--color-surface-light': '#2d3f30',
      '--color-accent': '#84cc16',
      '--color-accent-soft': '#65a30d',
      '--color-accent-glow': 'rgba(132, 204, 22, 0.10)',
      '--color-text': '#f0fdf4',
      '--color-text-dim': '#a3b8a8',
      '--color-text-muted': '#6b8070',
    },
  },
}

export const THEME_IDS = Object.keys(THEMES)
export const DEFAULT_THEME = 'midnight'
